### ISSUE TITLE
Buggy behavior when used with includePaths

### ISSUE THREAD

**Issue by mike3run** [shmargum/vim-sass-colors#2]
I like to use includePaths on my gulp-sass configs to avoid 2 major things:

- Manually copying the sass of a project that is already in my node_modules

- Having to do: `../../../..` infinite 😛 

So adding that param you add the path to where you'd like to be able to import things like magic (kind of like with the sass-loader of web pack that you can do `@import "~bootstrap/bootstrap.scss";`

So my guess is the plugin can't seem to follow those magic imports and in a lot of projects I'm getting these kind of logs

![screen shot 2017-06-14 at 12 04 13 am](https://user-images.githubusercontent.com/7088511/27116219-9bffd060-5095-11e7-9fd1-c436f8a930eb.png)

If there's any way I could help I'll be glad to contribute, this plugin is something really cool that brings the best of pigments to vim ❤️

**Comment by shmargum** [comment]
Thanks for submitting an issue and using the plugin!

I have pushed out a small patch that should resolve the error in the image you added.  I don't usually use vim split and forgot to test things out that way, though I was not able to get those same error messages.

As far as the magic imports of sass, this is a no simple issue since many different applications have different magic.  I have some ideas how to make this work (a little) better but any suggestions are greatly appreciated.


These are my current thoughts for how we can make imports more robust:

One thing that would be relatively simple to add would be to add a user option to define any import paths for the plugin, but I feel like that kind of defeats the point, as I think this plugin should mostly just work like magic and not require you to add anything custom (though would not be detrimental to simply have as an option).  This is briefly mentioned in the future plans for the plugin, but I am not too excited about having to manually input my imports just to get highlighting.

Adding a few more 'default' stylesheet directory import matches would be extremely simple, like 'styles' or something, but would likely not resolve your issue.

I tried to make it so that the plugin searches for the closest folder that is a git project, then imports _all_ sass/scss files from within that repo.  This created some weird behavior like compass overriding some of my colors.  There was also a slight delay in load time, but not too significant.
While this idea did not work as well as I would have hoped, I do like using the .git folder as an indicator of where the project root is and may move forward with that, but I don't think it would really change the current behavior.


I am currently using this plugin primarily within a rails app so most of the rules about imports, especially the 'magic' are based on my (generic) folder structure and intuition.

I think it would be best to add support for generic types of project 1 by 1.  The current logic is not very rails specific, but I would support looking for specific files that define your projects import paths and parsing those.  This includes things like adding support for parsing of things that define sass include paths like gulp-sass or sass-loader.


Currently, the file importing is all done in ruby, you can check out the importing logic here (but this won't help you import paths that are not explicitly included somewhere in the chain of includes of your file):
https://github.com/shmargum/vim-sass-colors/blob/a79d9867cd24429fa6e91b94f5aa7026da72ec3c/autoload/sass-colors.rb#L351-L404
And also currently the only real 'magic' import is just to look for a 'colors.scss' file (but we can augment this):
https://github.com/shmargum/vim-sass-colors/blob/a79d9867cd24429fa6e91b94f5aa7026da72ec3c/autoload/sass-colors.rb#L454-L463

Just a note here, when I simply globbed for all sass files within my project root (the folder containing a .git folder) I was able to delete all that code and bypass all of the above logic, but ended up having too many imports :/

**Comment by mike3run** [comment]
I've been testing this after last week, and I'm still getting those errors like the one on my previous screenshot, most notably when doing a commit from vim fugitive and coming back to the current buffer.

I'm not very fluent in ruby I'm sorry 😢 I couldn't really read your code. 

However I'm not so sure the ruby version of sass has includePaths, maybe thats a node-sass thing only 😕

**Comment by shmargum** [comment]
I don't really use vim fugitive but i tried it out and couldn't reproduce the issues.  I was however able to get some issues when playing around with vim splits by opening and closing the same files within the same vim session.  I ultimately ended up separating the clearing of matches exclusively to the write autocmd hook, and added support for reading new buffers.  Let me know if this fixes your issue.

As far as the includePaths thing goes, what does your project directory look like, including the file you are editing and the file you want to include, and what does the relevant lines that are declared in includePaths?

**Comment by mike3run** [comment]
hey there @shmargum maybe this could be added for the includePaths situation somehow?

https://github.com/lucasmotta/sass-module-importer

But then again that'd mean moving to node instead of ruby for the interpreter
